language: generic
dist: trusty

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

aliases:
  - &pg-ver 9.6

jobs:
  include:

    # === core tests
    - stage: ❧ pdb tests
      env: PDB_TEST=core/openjdk8
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: jdk_switcher use openjdk8 && ext/travisci/run-core-tests

    - stage: ❧ pdb tests
      env: PDB_TEST=core/oraclejdk8
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: jdk_switcher use oraclejdk8 && ext/travisci/run-core-tests

    # === integration tests
    - stage: ❧ pdb tests
      env: PDB_TEST=int/openjdk8/pup-master/srv-master
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: >-
        jdk_switcher use openjdk8
        && ext/travisci/run-integration-tests master master

    - stage: ❧ pdb tests
      env: PDB_TEST=int/oraclejdk8/pup-master/srv-master
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: >-
        jdk_switcher use oraclejdk8
        && ext/travisci/run-integration-tests master master

    - stage: ❧ pdb tests
      env: PDB_TEST=int/openjdk8/pup-5.5.x/srv-5.3.x
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: >-
        jdk_switcher use openjdk8
        && ext/travisci/run-integration-tests 5.5.x 5.3.x

    - stage: ❧ pdb tests
      env: PDB_TEST=int/oraclejdk8/pup-5.5.x/srv-5.3.x
      addons:
        postgresql: *pg-ver
      services: postgresql
      script: >-
        jdk_switcher use oraclejdk8
        && ext/travisci/run-integration-tests 5.5.x 5.3.x

    # === rspec tests
    - stage: ❧ pdb tests
      env: PDB_TEST=rspec/pup-master
      script: ext/travisci/run-rspec-tests master

    - stage: ❧ pdb tests
      env: PDB_TEST=rspec/pup-5.5.x
      script: ext/travisci/run-rspec-tests 5.5.x

before_install: ext/bin/host-info

on_success: ext/travisci/on-success

notifications:
  email: false
  hipchat:
    rooms:
      secure: gZpfMrGsUEHKzHfDaq8S00Xd35gzwEzcAy5/VV7JOGcmXLyWlx7ojh/Ke4rJ1vOa59OlazyCt5o8uDhB0CcQnZ2Aa6ncoOyLpLLjO8/Ak8qsxPLgC4Ov/zuRA4oTvxqZtaR7Juwbeobp5lB1OSFb7o4G747tC2Ihd1Nhx717tdQ=
    template: >-
      %{commit_subject}
      / %{repository} %{branch} <a href="%{compare_url}">%{commit}</a> %{author}
      / <a href="%{build_url}">#%{build_number}</a> %{result} in %{elapsed_time}
    format: html
